### ISSUE TITLE
git

### ISSUE THREAD

**Issue by skdonghyun** [skdonghyun/VectorDBTestData#11]
네, 드롭다운 메뉴를 추가하겠습니다. HTML과 CSS를 수정하고, 간단한 JavaScript를 추가하여 드롭다운 기능을 구현하겠습니다.

먼저 HTML:

```html
<nav class="nav-bar">
  <div class="nav-logo">
    <img src="nike-logo.png" alt="Nike Logo">
  </div>
  <ul class="nav-menu">
    <li><a href="#">New Releases</a></li>
    <li class="dropdown">
      <a href="#" class="dropbtn">Men</a>
      <div class="dropdown-content">
        <a href="#">신발</a>
        <a href="#">의류</a>
        <a href="#">악세서리</a>
      </div>
    </li>
    <li class="dropdown">
      <a href="#" class="dropbtn">Women</a>
      <div class="dropdown-content">
        <a href="#">신발</a>
        <a href="#">의류</a>
        <a href="#">악세서리</a>
      </div>
    </li>
    <li><a href="#">Kids</a></li>
    <li><a href="#">Sale</a></li>
  </ul>
  <div class="nav-icons">
    <a href="#" class="icon-search">검색</a>
    <a href="#" class="icon-cart">장바구니</a>
  </div>
</nav>
```

CSS:

```css
.nav-bar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0 20px;
  background-color: #fff;
  height: 60px;
}

.nav-logo img {
  height: 40px;
}

.nav-menu {
  display: flex;
  list-style-type: none;
}

.nav-menu li {
  margin: 0 15px;
}

.nav-menu a {
  text-decoration: none;
  color: #000;
  font-weight: bold;
}

.nav-icons a {
  margin-left: 20px;
  text-decoration: none;
  color: #000;
}

/* 드롭다운 스타일 */
.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown-content a:hover {
  background-color: #f1f1f1;
}

.dropdown:hover .dropdown-content {
  display: block;
}
```

JavaScript (선택적):

```javascript
document.querySelectorAll('.dropdown').forEach(function(dropdownWrapper) {
    const dropdownBtn = dropdownWrapper.querySelector('.dropbtn');
    const dropdownContent = dropdownWrapper.querySelector('.dropdown-content');
    
    dropdownBtn.addEventListener('click', function(e) {
        e.preventDefault();
        dropdownContent.style.display = dropdownContent.style.display === 'block' ? 'none' : 'block';
    });
    
    // 드롭다운 외부 클릭 시 닫기
    document.addEventListener('click', function(e) {
        if (!dropdownWrapper.contains(e.target)) {
            dropdownContent.style.display = 'none';
        }
    });
});
```

이 코드는 다음과 같은 기능을 제공합니다:

1. Men과 Women 메뉴에 드롭다운을 추가했습니다.
2. CSS를 사용하여 hover 시 드롭다운이 표시되도록 했습니다.
3. 선택적으로 JavaScript를 추가하여 클릭으로도 드롭다운을 열고 닫을 수 있게 했습니다.

이 코드를 기반으로 더 많은 드롭다운 메뉴를 추가하거나, 스타일을 조정할 수 있습니다. 추가적인 수정이나 기능이 필요하신가요?
