### ISSUE TITLE
이슈

### ISSUE THREAD

**Issue by skdonghyun** [skdonghyun/VectorDBTestData#6]
화면에서 모델을 선택하는 부분을 추가하여 전체 코드를 업데이트해보겠습니다. 모델 선택을 위해 드롭다운을 사용하고, 선택된 모델에 따라 API를 호출하도록 하겠습니다.

### `ChatBox.js`

```javascript
import React, { useState } from 'react';
import ChatInput from './ChatInput';
import Message from './Message';
import './ChatBox.css';

const ChatBox = () => {
  const [messages, setMessages] = useState([]);
  const [isTyping, setIsTyping] = useState(false);
  const [model, setModel] = useState('llama');

  const apiUrls = {
    llama: 'http://localhost:8888',
    custom: 'http://localhost:8887',
  };

  const handleSendMessage = async (message) => {
    setMessages([...messages, { text: message, sender: 'user' }]);
    setIsTyping(true);

    const response = await fetch(`${apiUrls[model]}/v1/chat/completions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ message }),
    });

    const reader = response.body.getReader();
    const decoder = new TextDecoder('utf-8');
    let result = '';
    let done = false;

    while (!done) {
      const { value, done: doneReading } = await reader.read();
      done = doneReading;
      result += decoder.decode(value);
      setMessages((prevMessages) => {
        const newMessages = [...prevMessages];
        const lastMessage = newMessages[newMessages.length - 1];
        if (lastMessage.sender === 'bot') {
          lastMessage.text = result;
        } else {
          newMessages.push({ text: result, sender: 'bot' });
        }
        return newMessages;
      });
    }

    setIsTyping(false);
  };

  const handleModelChange = (e) => {
    setModel(e.target.value);
  };

  return (
    <div className="chat-box">
      <div className="model-selection">
        <label htmlFor="model">Select Model:</label>
        <select id="model" value={model} onChange={handleModelChange}>
          <option value="llama">Llama</option>
          <option value="custom">Custom</option>
        </select>
      </div>
      <div className="messages">
        {messages.map((message, index) => (
          <Message key={index} message={message} />
        ))}
      </div>
      {isTyping && <div className="typing-indicator">Typing...</div>}
      <ChatInput onSendMessage={handleSendMessage} />
    </div>
  );
};

export default ChatBox;
```

### `ChatInput.js`

```javascript
import React, { useState } from 'react';
import './ChatInput.css';

const ChatInput = ({ onSendMessage }) => {
  const [inputValue, setInputValue] = useState('');

  const handleChange = (e) => {
    setInputValue(e.target.value);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (inputValue.trim()) {
      onSendMessage(inputValue.trim());
      setInputValue('');
    }
  };

  return (
    <form className="chat-input" onSubmit={handleSubmit}>
      <input
        type="text"
        value={inputValue}
        onChange={handleChange}
        placeholder="Type your message..."
      />
      <button type="submit">Send</button>
    </form>
  );
};

export default ChatInput;
```

### `Message.js`

```javascript
import React from 'react';
import './Message.css';

const Message = ({ message }) => {
  return (
    <div className={`message ${message.sender}`}>
      <div className="message-content">{message.text}</div>
    </div>
  );
};

export default Message;
```

### `ChatBox.css`

```css
.chat-box {
  display: flex;
  flex-direction: column;
  height: 100%;
  border: 1px solid #ccc;
  padding: 10px;
  box-sizing: border-box;
}

.model-selection {
  margin-bottom: 10px;
}

.model-selection label {
  margin-right: 10px;
}

.messages {
  flex-grow: 1;
  overflow-y: auto;
}

.typing-indicator {
  font-style: italic;
  color: #888;
}
```

### `ChatInput.css`

```css
.chat-input {
  display: flex;
  padding: 10px;
  border-top: 1px solid #ccc;
}

.chat-input input {
  flex-grow: 1;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 4px;
  margin-right: 10px;
}

.chat-input button {
  padding: 10px 20px;
  border: none;
  background-color: #007bff;
  color: #fff;
  border-radius: 4px;
  cursor: pointer;
}
```

### `Message.css`

```css
.message {
  margin: 10px 0;
}

.message.user .message-content {
  background-color: #dcf8c6;
  align-self: flex-end;
}

.message.bot .message-content {
  background-color: #fff;
}

.message-content {
  padding: 10px;
  border-radius: 4px;
  max-width: 60%;
}
```

이제 `ChatBox` 컴포넌트에 모델 선택 기능이 추가되었습니다. 사용자는 드롭다운 메뉴를 통해 `Llama` 모델과 `Custom` 모델 중 하나를 선택할 수 있습니다. 선택된 모델에 따라 채팅 메시지를 보낼 때 적절한 API 엔드포인트를 호출하게 됩니다.
