### ISSUE TITLE
이슈2

### ISSUE THREAD

**Issue by skdonghyun** [skdonghyun/VectorDBTestData#7]
다음은 남은 파일들에 대한 코드 작성입니다. 로그인 페이지는 필요 없으므로 `LoginPage.js`는 생략하겠습니다.

### `Header.js`

```javascript
import React from 'react';
import './Header.css';

const Header = () => {
  return (
    <header className="header">
      <h1>My Chat App</h1>
    </header>
  );
};

export default Header;
```

### `Sidebar.js`

```javascript
import React from 'react';
import './Sidebar.css';

const Sidebar = () => {
  return (
    <aside className="sidebar">
      <ul>
        <li>Home</li>
        <li>Settings</li>
        <li>About</li>
      </ul>
    </aside>
  );
};

export default Sidebar;
```

### `ChatPage.js`

```javascript
import React from 'react';
import Header from '../components/Header';
import Sidebar from '../components/Sidebar';
import ChatBox from '../components/Chat/ChatBox';
import './ChatPage.css';

const ChatPage = () => {
  return (
    <div className="chat-page">
      <Header />
      <div className="main-content">
        <Sidebar />
        <ChatBox />
      </div>
    </div>
  );
};

export default ChatPage;
```

### `api.js`

```javascript
export const sendMessage = async (message, apiUrl) => {
  const response = await fetch(`${apiUrl}/v1/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ message }),
  });

  return response.body.getReader();
};
```

### `helpers.js`

```javascript
export const decodeStream = async (reader) => {
  const decoder = new TextDecoder('utf-8');
  let result = '';
  let done = false;

  while (!done) {
    const { value, done: doneReading } = await reader.read();
    done = doneReading;
    result += decoder.decode(value);
  }

  return result;
};
```

### `App.js`

```javascript
import React from 'react';
import ChatPage from './pages/ChatPage';
import './styles/global.css';

const App = () => {
  return (
    <div className="app">
      <ChatPage />
    </div>
  );
};

export default App;
```

### `index.js`

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import './styles/global.css';

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);
```

### `global.css`

```css
body {
  margin: 0;
  font-family: Arial, sans-serif;
  background-color: #f5f5f5;
}

* {
  box-sizing: border-box;
}

.app {
  display: flex;
  flex-direction: column;
  height: 100vh;
}

.main-content {
  display: flex;
  flex-grow: 1;
}
```

### `Header.css`

```css
.header {
  background-color: #007bff;
  color: #fff;
  padding: 10px;
  text-align: center;
}
```

### `Sidebar.css`

```css
.sidebar {
  width: 200px;
  background-color: #f8f9fa;
  padding: 10px;
  border-right: 1px solid #ccc;
}

.sidebar ul {
  list-style-type: none;
  padding: 0;
}

.sidebar li {
  margin: 10px 0;
  cursor: pointer;
}
```

### `ChatPage.css`

```css
.chat-page {
  display: flex;
  flex-direction: column;
  height: 100vh;
}

.main-content {
  display: flex;
  flex-grow: 1;
}
```

### `index.html`

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>My Chat App</title>
</head>
<body>
  <div id="root"></div>
</body>
</html>
```

### `.gitignore`

```plaintext
node_modules/
dist/
build/
.env
.DS_Store
```

### `package.json`

```json
{
  "name": "my-chat-app",
  "version": "1.0.0",
  "description": "A simple chat application using React.js",
  "main": "src/index.js",
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3"
  },
  "devDependencies": {},
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

### `README.md`

```markdown
# My Chat App

This is a simple chat application built using React.js.

## Features

- Send and receive messages in real-time
- Choose between different language models (Llama and Custom)

## Setup

1. Clone the repository:
   ```sh
   git clone https://github.com/your-username/my-chat-app.git
   ```

2. Navigate to the project directory:
   ```sh
   cd my-chat-app
   ```

3. Install dependencies:
   ```sh
   npm install
   ```

4. Start the development server:
   ```sh
   npm start
   ```

The application should now be running at `http://localhost:3000`.

## Project Structure

- `public/`: Contains the HTML file and static assets
- `src/`: Contains the source code
  - `assets/`: Contains images and other asset files
  - `components/`: Contains React components
  - `pages/`: Contains page components
  - `services/`: Contains API service functions
  - `utils/`: Contains utility functions
  - `App.js`: Main App component
  - `index.js`: Entry point of the React application
  - `styles/`: Contains global and component-specific CSS files

## License

This project is licensed under the MIT License.
```

이제 전체 프로젝트 구조와 모든 파일들이 작성되었습니다. 이 구조를 사용하여 React 기반의 채팅 애플리케이션을 구축할 수 있습니다. 모델 선택 기능과 스트리밍 응답 처리를 포함한 주요 기능이 구현되었습니다.
